return {
    "ThePrimeagen/harpoon",
    config = function()
        local mark = require("harpoon.mark")
        local ui = require("harpoon.ui")

        vim.keymap.set("n", "<leader>a", mark.add_file, { desc = "Harpoon: Add file" })
        vim.keymap.set("n", "<C-e>", ui.toggle_quick_menu, { desc = "Harpoon: Toggle quick menu" })

        vim.keymap.set("n", "<F1>", function()
            ui.nav_file(1)
        end, { desc = "Harpoon: Nav file 1" })
        vim.keymap.set("n", "<F2>", function()
            ui.nav_file(2)
        end, { desc = "Harpoon: Nav file 2" })
        vim.keymap.set("n", "<F3>", function()
            ui.nav_file(3)
        end, { desc = "Harpoon: Nav file 3" })
        vim.keymap.set("n", "<F4>", function()
            ui.nav_file(4)
        end, { desc = "Harpoon: Nav file 4" })
        vim.keymap.set("n", "<F5>", function()
            ui.nav_file(5)
        end, { desc = "Harpoon: Nav file 5" })
        vim.keymap.set("n", "<F6>", function()
            ui.nav_file(6)
        end, { desc = "Harpoon: Nav file 6" })

        vim.keymap.set("n", "<C-1>", function()
            ui.nav_file(1)
        end, { desc = "Harpoon: Nav file 1" })
        vim.keymap.set("n", "<C-2>", function()
            ui.nav_file(2)
        end, { desc = "Harpoon: Nav file 2" })
        vim.keymap.set("n", "<C-3>", function()
            ui.nav_file(3)
        end, { desc = "Harpoon: Nav file 3" })
        vim.keymap.set("n", "<C-4>", function()
            ui.nav_file(4)
        end, { desc = "Harpoon: Nav file 4" })
        vim.keymap.set("n", "<C-5>", function()
            ui.nav_file(5)
        end, { desc = "Harpoon: Nav file 5" })
        vim.keymap.set("n", "<C-6>", function()
            ui.nav_file(6)
        end, { desc = "Harpoon: Nav file 6" })

        vim.keymap.set("n", "<A-1>", function()
            ui.nav_file(1)
        end, { desc = "Harpoon: Nav file 1" })

        vim.keymap.set("n", "<A-2>", function()
            ui.nav_file(2)
        end, { desc = "Harpoon: Nav file 2" })

        vim.keymap.set("n", "<A-3>", function()
            ui.nav_file(3)
        end, { desc = "Harpoon: Nav file 3" })

        vim.keymap.set("n", "<A-4>", function()
            ui.nav_file(4)
        end, { desc = "Harpoon: Nav file 4" })

        vim.keymap.set("n", "<A-5>", function()
            ui.nav_file(5)
        end, { desc = "Harpoon: Nav file 5" })

        vim.keymap.set("n", "<A-6>", function()
            ui.nav_file(6)
        end, { desc = "Harpoon: Nav file 6" })
    end,
}
